// SWAGPH - Unified Authentication Logic Engine (Synchronized)

const loginForm = document.getElementById('login-form');
const emailInput = document.getElementById('email');
const passwordInput = document.getElementById('password');
const loginBtn = document.getElementById('login-btn');
const emailError = document.getElementById('email-error');
const passwordError = document.getElementById('password-error');
const loginFailed = document.getElementById('login-failed');
const togglePassword = document.getElementById('toggle-password');
const formWrapper = document.querySelector('.form-wrapper');

function validateEmail(email) {
  return /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email);
}

function updateButtonState() {
  const email = emailInput.value.trim();
  const password = passwordInput.value;
  loginBtn.disabled = !(email.length >= 1 && password.length >= 1);
}

function showError(input, message) {
  if (input === 'email') {
    emailError.textContent = message;
  } else if (input === 'password') {
    passwordError.textContent = message;
  }
}

function clearErrors() {
  emailError.textContent = '';
  passwordError.textContent = '';
  if (loginFailed) {
    loginFailed.textContent = '';
    loginFailed.style.display = 'none';
  }
}

function setAuthenticating(state) {
  if (state) {
    loginBtn.textContent = 'Authenticating...';
    loginBtn.disabled = true;
  } else {
    loginBtn.textContent = 'Login';
    updateButtonState();
  }
}

function shakeForm() {
  if (formWrapper) {
    formWrapper.classList.add('shake');
    setTimeout(() => {
      formWrapper.classList.remove('shake');
    }, 500);
  }
}

// MATCHING ENGINE RULE: Ensure we align with your registration baseline definitions
function ensureUserTable() {
  if (!localStorage.getItem('user_table')) {
    const initialUsers = [
      {
        u_id: 'ADM001',
        u_name: 'System Admin',
        u_email: 'admin@swagph.com',
        u_pass: 'Admin123',
        u_role: 'ADMIN',
        u_phone: 'N/A',
        u_created: new Date().toLocaleDateString()
      }
    ];
    localStorage.setItem('user_table', JSON.stringify(initialUsers));
  }
}

function getUserTable() {
  const stored = localStorage.getItem('user_table');
  try {
    return stored ? JSON.parse(stored) : [];
  } catch (error) {
    console.error('Failed to parse user_table from localStorage', error);
    return [];
  }
}

function saveSession(user) {
  const currentSession = {
    id: user.u_id,
    name: user.u_name,
    email: user.u_email,
    role: user.u_role
  };
  localStorage.setItem('swag_session', JSON.stringify(currentSession));
}

function routeByRole(role) {
  if (role === 'ADMIN') {
    window.location.href = 'admin.html';
  } else if (role === 'CLIENT') {
    window.location.href = 'client-dashboard.html';
  } else {
    const message = 'Critical System error: User account does not possess a valid security role.';
    if (loginFailed) {
      loginFailed.textContent = message;
      loginFailed.style.display = 'block';
    } else {
      alert(message);
    }
    localStorage.removeItem('swag_session');
  }
}

if (loginForm) {
  ensureUserTable();

  emailInput.addEventListener('input', () => {
    clearErrors();
    const email = emailInput.value.trim();
    if (email.length > 0 && !validateEmail(email)) {
      showError('email', 'Enter a valid email.');
    }
    updateButtonState();
  });

  passwordInput.addEventListener('input', () => {
    clearErrors();
    updateButtonState();
  });

  if (togglePassword) {
    let passwordVisible = false;
    togglePassword.addEventListener('click', () => {
      passwordVisible = !passwordVisible;
      passwordInput.type = passwordVisible ? 'text' : 'password';
      togglePassword.textContent = passwordVisible ? '👁️' : '🙈';
    });
  }

  loginForm.addEventListener('submit', (e) => {
    e.preventDefault();
    clearErrors();
    setAuthenticating(true);

    const email = emailInput.value.trim().toLowerCase();
    const password = passwordInput.value;
    const userTable = getUserTable();

    // Matching exact field strings generated by your register logic controller
    const matchedUser = userTable.find(user =>
      user.u_email.toLowerCase() === email && user.u_pass === password
    );

    setTimeout(() => {
      if (!matchedUser) {
        if (loginFailed) {
          loginFailed.textContent = 'Invalid email address or access password credentials.';
          loginFailed.style.display = 'block';
        } else {
          alert('Invalid email address or access password credentials.');
        }
        shakeForm();
        setAuthenticating(false);
        return;
      }

      saveSession(matchedUser);
      routeByRole(matchedUser.u_role);
    }, 400);
  });

  updateButtonState();
} else {
  console.warn('Login form not found on this page.');
}